In [1]:
#imports
import pandas as pd

In [4]:
df = pd.read_csv("annual_aqi_by_cbsa_2024.csv")
df.head()

,CBSA,CBSA Code,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days PM2.5,Days PM10
0,"Aberdeen, SD",10100,2024,357,306,47,4,0,0,0,118,54,24,0,0,0,239,118
1,"Aberdeen, WA",10140,2024,366,353,13,0,0,0,0,64,36,20,0,0,0,366,0
2,"Ada, OK",10220,2024,289,207,81,1,0,0,0,101,63,43,0,0,183,105,1
3,"Adrian, MI",10300,2024,366,253,113,0,0,0,0,97,59,43,0,0,172,194,0
4,"Akron, OH",10420,2024,341,216,123,2,0,0,0,108,71,45,0,0,175,166,0

In [ ]:
print(df.shape)
print(df.dtypes)

(501, 18)
CBSA                                   object
CBSA Code                               int64
Year                                    int64
Days with AQI                           int64
Good Days                               int64
Moderate Days                           int64
Unhealthy for Sensitive Groups Days     int64
Unhealthy Days                          int64
Very Unhealthy Days                     int64
Hazardous Days                          int64
Max AQI                                 int64
90th Percentile AQI                     int64
Median AQI                              int64
Days CO                                 int64
Days NO2                                int64
Days Ozone                              int64
Days PM2.5                              int64
Days PM10                               int64
dtype: object
CBSA                                   0
CBSA Code                              0
Year                                   0
Days with AQI                          0
Good Days                              0
Moderate Days                          0
Unhealthy for Sensitive Groups Days    0
Unhealthy Days                         0
Very Unhealthy Days                    0
Hazardous Days                         0
Max AQI                                0
90th Percentile AQI                    0
Median AQI                             0
Days CO                                0
Days NO2                               0
Days Ozone                             0
Days PM2.5                             0
Days PM10                              0
dtype: int64

In [17]:
#Dataset Cleaning
df = df.dropna()
df = df.drop_duplicates()

df.shape

(501, 19)

In [18]:
df.describe()

,CBSA Code,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days PM2.5,Days PM10,total_check
count,501.000000,501.0,501.000000,501.000000,501.000000,501.000000,501.000000,501.000000,501.000000,501.000000,501.000000,501.000000,501.000000,501.000000,501.000000,501.000000,501.000000,501.000000
mean,29932.614770,2024.0,342.610778,237.301397,99.483034,4.732535,0.912176,0.135729,0.045908,125.760479,62.756487,41.197605,0.544910,1.075848,159.750499,168.796407,12.443114,342.610778
std,11415.684603,0.0,60.396011,72.328715,63.051584,11.366984,4.615222,1.270252,0.351978,102.536562,17.810912,10.761174,10.011218,3.705433,107.084806,112.218637,48.795320,60.396011
min,10100.000000,2024.0,31.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,31.000000,17.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,31.000000
25%,20060.000000,2024.0,359.000000,198.000000,49.000000,0.000000,0.000000,0.000000,0.000000,87.000000,54.000000,37.000000,0.000000,0.000000,89.000000,85.000000,0.000000,359.000000
50%,29660.000000,2024.0,366.000000,246.000000,90.000000,1.000000,0.000000,0.000000,0.000000,105.000000,60.000000,42.000000,0.000000,0.000000,163.000000,172.000000,0.000000,366.000000
75%,40060.000000,2024.0,366.000000,291.000000,141.000000,4.000000,0.000000,0.000000,0.000000,140.000000,67.000000,47.000000,0.000000,0.000000,229.000000,241.000000,1.000000,366.000000
max,49740.000000,2024.0,366.000000,364.000000,267.000000,102.000000,71.000000,26.000000,4.000000,1513.000000,185.000000,97.000000,223.000000,37.000000,365.000000,366.000000,366.000000,366.000000

In [ ]:
#Average AQIs for each 
f[["Good Days","Moderate Days", "Unhealthy for Sensitive Groups Days","Unhealthy Days","Very Unhealthy Days", "Hazardous Days"]].mean()

Good Days                              237.301397
Moderate Days                           99.483034
Unhealthy for Sensitive Groups Days      4.732535
Unhealthy Days                           0.912176
Very Unhealthy Days                      0.135729
Hazardous Days                           0.045908
dtype: float64

In [ ]:
#Worst AQIs
df.groupby("CBSA")["Median AQI"].mean().sort_values(ascending=False).head()

CBSA
Riverside-San Bernardino-Ontario, CA    97.0
Phoenix-Mesa-Scottsdale, AZ             86.0
Los Angeles-Long Beach-Anaheim, CA      80.0
Bakersfield, CA                         72.0
San Diego-Carlsbad, CA                  71.0
Name: Median AQI, dtype: float64

In [22]:
#Best AQIs
df.groupby("CBSA")["Median AQI"].mean().sort_values(ascending=True).head()

CBSA
Ponce, PR        3.0
Evanston, WY     7.0
Pierre, SD       8.0
Mayaguez, PR    11.0
Houghton, MI    12.0
Name: Median AQI, dtype: float64