In [1]:
import pandas as pd

In [2]:
aqi_df = pd.read_csv("annual_aqi_by_cbsa_2024.csv")
crime_df = pd.read_csv("crime_cleaned.csv")

In [3]:
aqi_df.head()

,CBSA,CBSA Code,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days PM2.5,Days PM10
0,"Aberdeen, SD",10100,2024,357,306,47,4,0,0,0,118,54,24,0,0,0,239,118
1,"Aberdeen, WA",10140,2024,366,353,13,0,0,0,0,64,36,20,0,0,0,366,0
2,"Ada, OK",10220,2024,289,207,81,1,0,0,0,101,63,43,0,0,183,105,1
3,"Adrian, MI",10300,2024,366,253,113,0,0,0,0,97,59,43,0,0,172,194,0
4,"Akron, OH",10420,2024,341,216,123,2,0,0,0,108,71,45,0,0,175,166,0

In [4]:
crime_df.head()

,state,city,population,violent_crime,murder,rape,robbery,aggravated_assault,property_crime,burglary,larceny_theft,motor_vehicle_theft,arson
0,ALABAMA,Adamsville,4111.0,23.0,1.0,1.0,0.0,21.0,130.0,12.0,97.0,21.0,2.0
1,ALABAMA,Addison,669.0,3.0,0.0,0.0,0.0,3.0,13.0,4.0,7.0,2.0,0.0
2,ALABAMA,Alabaster,34349.0,34.0,0.0,1.0,4.0,29.0,519.0,17.0,480.0,22.0,0.0
3,ALABAMA,Albertville,23242.0,55.0,1.0,14.0,3.0,37.0,409.0,65.0,299.0,45.0,2.0
4,ALABAMA,Alexander City,14353.0,147.0,4.0,7.0,11.0,125.0,515.0,91.0,398.0,26.0,5.0

In [10]:
import pandas as pd

aqi_df['city'] = aqi_df['CBSA'].str.split(',').str[0]
aqi_df['city'] = aqi_df['city'].str.split('-').str[0]
aqi_df['city'] = aqi_df['city'].str.strip().str.lower()
crime_df['city'] = crime_df['city'].str.strip().str.lower()

In [11]:
merged = pd.merge(aqi_df, crime_df, on='city', how='inner')

In [12]:
merged.head()

,CBSA,CBSA Code,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,...,violent_crime,murder,rape,robbery,aggravated_assault,property_crime,burglary,larceny_theft,motor_vehicle_theft,arson
0,"Aberdeen, SD",10100,2024,357,306,47,4,0,0,0,...,111.0,4.0,13.0,26.0,68.0,379.0,33.0,310.0,36.0,1.0
1,"Aberdeen, SD",10100,2024,357,306,47,4,0,0,0,...,24.0,0.0,0.0,0.0,24.0,320.0,49.0,256.0,15.0,3.0
2,"Aberdeen, SD",10100,2024,357,306,47,4,0,0,0,...,75.0,0.0,14.0,0.0,61.0,395.0,70.0,296.0,29.0,0.0
3,"Aberdeen, SD",10100,2024,357,306,47,4,0,0,0,...,63.0,0.0,22.0,13.0,28.0,506.0,49.0,404.0,53.0,7.0
4,"Aberdeen, WA",10140,2024,366,353,13,0,0,0,0,...,111.0,4.0,13.0,26.0,68.0,379.0,33.0,310.0,36.0,1.0